[project]
name = "optimizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.1",
    "dspy>=3.0.4",
    "ipdb>=0.13.13",
    "fastapi>=0.115.0",
    "uvicorn>=0.34.0",
]
